stages:
  - build
  - deploy

before_script:
  - export JAVA_HOME="/usr/local/jdk1.8.0_231"

build:
  tags:
    - dev
  stage: build
  script:
    - ./gradlew bootJar -Pprod

deploy:
  tags:
    - deploy
  stage: deploy
  only:
    - master
  script:
    - ./gradlew bootJar -Pprod jibDockerBuild -Djib.httpTimeout=0 -x test
    - docker-compose -p hermes -f src/main/docker/app.yml up -d
